title = 'blog.jroi.dev'
baseURL = 'https://blog.jroi.dev/'
languageCode = 'en-us'
copyright = '''
  Copyright 2023 Roi Martin.
  Unless otherwise noted, this work is licensed under
  <a href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.
  '''
disableKinds = ['taxonomy', 'term']

[params]
profileURLs = ['https://fosstodon.org/@jroimartin']
